version: '3.9'

services:
  postgresDb:
    container_name: PostgresDBContainer
    image: postgres:17.0-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres1
      - POSTGRES_PASSWORD=postgres1
      - POSTGRES_DB=TestDBInContainer


  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - './config/keycloak/import:/opt/keycloak/data/import'
    ports:
      - "8090:8080"
    command: start-dev --import-realm

  employees-service:
    container_name: Employees
    build:
      context: ./employees-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgresDb
    environment:
      - DB_URL=jdbc:postgresql://postgresDb:5432/TestDBInContainer
      - USER_DB=postgres1
      - PASSWORD_DB=postgres1


  log-entry-service:
    container_name: LogEntries
    build:
      context: ./log-entry-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - postgresDb
    environment:
      - DB_URL=jdbc:postgresql://postgresDb:5432/TestDBInContainer
      - USER_DB=postgres1
      - PASSWORD_DB=postgres1

  api-gateway:
    container_name: ApiGateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  frontend:
    container_name: Frontend
    build:
      context: ./time-tracker-ui
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api-gateway