name: TimeTrackerV2
services:
  postgresDb:
    container_name: PostgresDBContainer
    image: postgres:17.0-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres1
      - POSTGRES_PASSWORD=postgres1
      - POSTGRES_DB=TestDBInContainer
#    чтобы не падала кафка
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres1 -d TestDBInContainer" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped


  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:23.0.7
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: true
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: false
      # Добавляем для стабильности
      KC_DB: dev-file
      JAVA_OPTS: "-Xms512m -Xmx1024m"
    volumes:
      - './config/keycloak/import:/opt/keycloak/data/import'
    command: start-dev --import-realm
    #    чтобы не падала кафка
    healthcheck:
      test: ["CMD-SHELL", "echo > /dev/tcp/localhost/8080"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 120s
    restart: unless-stopped


  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
#     чтобы не падала кафка
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: [ "CMD-SHELL", "echo stat | nc localhost 2181 || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped


  kafka:
    image: confluentinc/cp-kafka:7.3.0
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # чтобы не падала кафка
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      # Увеличиваем таймауты для устойчивости
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS: 60000
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 60000
#        # Добавляем ретеншн для логов
#      KAFKA_LOG_RETENTION_HOURS: 168
#      KAFKA_LOG_SEGMENT_BYTES: 1073741824
#      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000
    healthcheck:
      test: [ "CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092" ]
      interval: 30s
      timeout: 20s
      retries: 10
      start_period: 60s
    restart: unless-stopped  #автоматический перезапуск при падении

#Раскомментировать для запуска в контейнере:
  employees-service:
    container_name: Employees
    build:
      context: ./employees-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      postgresDb:
        condition: service_healthy
      kafka:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    environment:
      - DB_URL=jdbc:postgresql://postgresDb:5432/TestDBInContainer
      - USER_DB=postgres1
      - PASSWORD_DB=postgres1
      - AUTH_SERVER_URL=http://keycloak:8080
      # Добавляем настройки Kafka для сервиса
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    restart: unless-stopped

  log-entry-service:
    container_name: LogEntries
    build:
      context: ./log-entry-service
      dockerfile: Dockerfile
#    build:
#      context: .
#      dockerfile: log-entry-service/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      postgresDb:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      - DB_URL=jdbc:postgresql://postgresDb:5432/TestDBInContainer
      - USER_DB=postgres1
      - PASSWORD_DB=postgres1
      - EMPLOYEE_URI=http://Employees:8081
      # Добавляем настройки Kafka для сервиса
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    restart: unless-stopped

  api-gateway:
    container_name: ApiGateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      employees-service:
        condition: service_started
      log-entry-service:
        condition: service_started
    environment:
      - FRONTEND_URI=http://localhost:3000
      - KEYCLOAK_URI=http://localhost:8080/realms/Employees_realm
      - EMPLOYEES_SERVICE_URI=http://Employees:8081
      - LOG_ENTRY_SERVICE_URI=http://LogEntries:8082
    extra_hosts:
      - "localhost:host-gateway"
    restart: unless-stopped

  mail-sender:
    container_name: MailSender
    build:
      context: ./mail-sender
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      kafka:
        condition: service_healthy
      employees-service:
        condition: service_started
    environment:
      - EMPLOYEE_URI=http://Employees:8081
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_MAIL_HOST=smtp.mail.ru
      - SPRING_MAIL_PORT=465
      - SPRING_MAIL_USERNAME=test-employee2@mail.ru
      - SPRING_MAIL_PASSWORD=CHANGE_PASSWORD
    restart: on-failure

  frontend:
    container_name: Frontend
    build:
      context: ./time-tracker-ui
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      api-gateway:
        condition: service_started

