spring:
#  application:
#    name: backendApp
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/TestDBInContainer}
    username: ${USER_DB:postgres1}
    password: ${PASSWORD_DB:postgres1}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    show-sql: true # Показывать SQL-запросы в логах (опционально)
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none # Отключаем автоматическое создание/обновление схемы
  liquibase:
    enabled: true # Включаем Liquibase
    change-log: classpath:db/changelog/db.changelog-master.xml # Указываем путь к главному файлу изменений
server:
  port: 8081

keycloak:
  auth-server-url: http://localhost:8090
  realm: master
  clientId: admin-cli
  userName: admin
  password: admin


#logging:
#  level:
#    root: info
#    org.example.backendapp: trace
##  file:
##    name: myLogs
#
#server:
#  port: ${PORT:8080}
#
#frontend:
#  url: ${FRONTEND_URL:http://localhost:3000}