spring:
  application:
    name: backendApp
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/TestDBInContainer}
    username: ${USER_DB:postgres1}
    password: ${PASSWORD_DB:postgres1}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: false
    change-log: db.changelog/db.changelog-master.xml

logging:
  level:
    root: info
    org.example.backendapp: trace
#  file:
#    name: myLogs

server:
  port: ${PORT:8080}

frontend:
  url: ${FRONTEND_URL:http://localhost:3000}